# PARAMETERS TO CONTROL THE BEHAVIOR OF THE GAME ENGINE
# DO NOT REMOVE OR RENAME THIS FILE
PLAYER_1_NAME = "python_skeleton (1)"
PLAYER_1_PATH = "python_skeleton"
# NO TRAILING SLASHES ARE ALLOWED IN PATHS
PLAYER_2_NAME = "python_skeleton (2)"
PLAYER_2_PATH = "python_skeleton"
# GAME PROGRESS IS RECORDED HERE
GAME_LOG_FILENAME = "logs/python_skeleton (1) vs. python_skeleton (2)-2023-01-11-031510"
# PLAYER_LOG_SIZE_LIMIT IS IN BYTES
PLAYER_LOG_SIZE_LIMIT = 524288
# STARTING_GAME_CLOCK AND TIMEOUTS ARE IN SECONDS
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 30.
BUILD_TIMEOUT = 10.
CONNECT_TIMEOUT = 10.
# THE GAME VARIANT FIXES THE PARAMETERS BELOW
# CHANGE ONLY FOR TRAINING OR EXPERIMENTATION
NUM_ROUNDS = 1000
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1
